# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys


class TestDangKy():
    def setup_method(self, method):
        # Khởi tạo trình duyệt Firefox
        self.driver = webdriver.Firefox()
        self.driver.implicitly_wait(10)

    def teardown_method(self, method):
        self.driver.quit()

    def safe_click(self, element_id):
        """Hàm dùng chung để click xuyên qua quảng cáo"""
        element = self.driver.find_element(By.ID, element_id)
        self.driver.execute_script("arguments[0].scrollIntoView(true);", element)
        self.driver.execute_script("arguments[0].click();", element)
        return element

    def clean_ads(self):
        """Mẹo xóa quảng cáo Somee gây lỗi Intercepted"""
        self.driver.execute_script("""
            var overlays = document.querySelectorAll('div[style*="z-index"], a[href*="somee.com"], iframe, center');
            for (var i = 0; i < overlays.length; i++) { overlays[i].remove(); }
            document.body.style.overflow = 'auto';
        """)
        time.sleep(1)

    def test_tC001(self):
        self.driver.get("http://hauiproj.somee.com/Default.aspx")
        self.driver.set_window_size(1382, 736)
        self.clean_ads()
        self.safe_click("LinkDK")
        self.safe_click("ContentPlaceHolder1_txtTaiKhoan").send_keys("anhday")
        self.safe_click("ContentPlaceHolder1_txtMatKhau").send_keys("12345")
        self.safe_click("ContentPlaceHolder1_txtHoTen").send_keys("Nguyễn Văn Sơn")
        self.safe_click("ContentPlaceHolder1_txtNamSinh").send_keys("2004-02-14")
        self.safe_click("ContentPlaceHolder1_txtEmail").send_keys("haui1234@gmail.com")
        self.safe_click("ContentPlaceHolder1_txtSdt").send_keys("0333127476")
        self.safe_click("ContentPlaceHolder1_txtDiaChi").send_keys("Số 296 Cầu Diễn, Hà Nội")
        self.safe_click("ContentPlaceHolder1_btDangky")

    def test_tC002(self):
        self.driver.get("http://hauiproj.somee.com/Default.aspx")
        self.clean_ads()
        self.safe_click("LinkDK")
        self.safe_click("ContentPlaceHolder1_txtMatKhau").send_keys("12345")
        self.safe_click("ContentPlaceHolder1_txtHoTen").send_keys("Đinh Văn La")
        self.safe_click("ContentPlaceHolder1_txtNamSinh").send_keys("2005-10-02")
        self.safe_click("ContentPlaceHolder1_txtEmail").send_keys("hauipro123@gmail.com")
        self.safe_click("ContentPlaceHolder1_txtSdt").send_keys("0125478954")
        self.safe_click("ContentPlaceHolder1_txtDiaChi").send_keys("DHCN Hà Nội")
        self.safe_click("ContentPlaceHolder1_btDangky")
        # Assert chờ text xuất hiện
        WebDriverWait(self.driver, 10).until(
            EC.text_to_be_present_in_element((By.ID, "ContentPlaceHolder1_lblThongBao"), "Nhập tài khoản"))
        assert "Nhập tài khoản" in self.driver.find_element(By.ID, "ContentPlaceHolder1_lblThongBao").text

    def test_tC003(self):
        self.driver.get("http://hauiproj.somee.com/Default.aspx")
        self.clean_ads()
        self.safe_click("LinkDK")
        self.safe_click("ContentPlaceHolder1_txtTaiKhoan").send_keys("lanh")
        self.safe_click("ContentPlaceHolder1_txtHoTen").send_keys("Đinh Văn Hà")
        self.safe_click("ContentPlaceHolder1_txtNamSinh").send_keys("1996-01-02")
        self.safe_click("ContentPlaceHolder1_txtEmail").send_keys("hauipro123@gmail.com")
        self.safe_click("ContentPlaceHolder1_txtSdt").send_keys("0789451237")
        self.safe_click("ContentPlaceHolder1_txtDiaChi").send_keys("DHCN Hà Nội")
        self.safe_click("ContentPlaceHolder1_btDangky")
        WebDriverWait(self.driver, 10).until(
            EC.text_to_be_present_in_element((By.ID, "ContentPlaceHolder1_lblThongBao"), "Nhập mật khẩu"))
        assert "Nhập mật khẩu" in self.driver.find_element(By.ID, "ContentPlaceHolder1_lblThongBao").text

    def test_tC004(self):
        self.driver.get("http://hauiproj.somee.com/Default.aspx")
        self.clean_ads()
        self.safe_click("LinkDK")
        self.safe_click("ContentPlaceHolder1_txtTaiKhoan").send_keys("abc")
        self.safe_click("ContentPlaceHolder1_txtMatKhau").send_keys("abc")
        self.safe_click("ContentPlaceHolder1_txtNamSinh").send_keys("2002-11-14")
        self.safe_click("ContentPlaceHolder1_txtEmail").send_keys("hauipro123@gmail.com")
        self.safe_click("ContentPlaceHolder1_txtSdt").send_keys("0125478957")
        self.safe_click("ContentPlaceHolder1_txtDiaChi").send_keys("DHCN Hà Nội")
        self.safe_click("ContentPlaceHolder1_btDangky")
        WebDriverWait(self.driver, 10).until(
            EC.text_to_be_present_in_element((By.ID, "ContentPlaceHolder1_lblThongBao"), "Nhập họ tên"))
        assert "Nhập họ tên" in self.driver.find_element(By.ID, "ContentPlaceHolder1_lblThongBao").text

    def test_tC005(self):
        self.driver.get("http://hauiproj.somee.com/Default.aspx")
        self.clean_ads()
        self.safe_click("LinkDK")
        self.safe_click("ContentPlaceHolder1_txtTaiKhoan").send_keys("abc")
        self.safe_click("ContentPlaceHolder1_txtMatKhau").send_keys("abc")
        self.safe_click("ContentPlaceHolder1_txtHoTen").send_keys("Trần Văn Đa")
        self.safe_click("ContentPlaceHolder1_txtEmail").send_keys("hauipro123@gmail.com")
        self.safe_click("ContentPlaceHolder1_txtSdt").send_keys("0125478954")
        self.safe_click("ContentPlaceHolder1_txtDiaChi").send_keys("DHCN Hà Nội")
        self.safe_click("ContentPlaceHolder1_btDangky")
        WebDriverWait(self.driver, 10).until(
            EC.text_to_be_present_in_element((By.ID, "ContentPlaceHolder1_lblThongBao"), "Chọn ngày sinh"))
        assert "Chọn ngày sinh" in self.driver.find_element(By.ID, "ContentPlaceHolder1_lblThongBao").text

    def test_tC006(self):
        self.driver.get("http://hauiproj.somee.com/Default.aspx")
        self.clean_ads()
        self.safe_click("LinkDK")
        self.safe_click("ContentPlaceHolder1_txtTaiKhoan").send_keys("abc")
        self.safe_click("ContentPlaceHolder1_txtMatKhau").send_keys("abc")
        self.safe_click("ContentPlaceHolder1_txtHoTen").send_keys("TRần Văn Hà")
        self.safe_click("ContentPlaceHolder1_txtNamSinh").send_keys("2002-11-14")
        self.safe_click("ContentPlaceHolder1_txtSdt").send_keys("0125478951")
        self.safe_click("ContentPlaceHolder1_txtDiaChi").send_keys("DHCN Hà Nội")
        self.safe_click("ContentPlaceHolder1_btDangky")
        WebDriverWait(self.driver, 10).until(
            EC.text_to_be_present_in_element((By.ID, "ContentPlaceHolder1_lblThongBao"), "Nhập Email"))
        assert "Nhập Email" in self.driver.find_element(By.ID, "ContentPlaceHolder1_lblThongBao").text

    def test_tC007(self):
        self.driver.get("http://hauiproj.somee.com/Default.aspx")
        self.clean_ads()
        self.safe_click("LinkDK")
        self.safe_click("ContentPlaceHolder1_txtTaiKhoan").send_keys("abc")
        self.safe_click("ContentPlaceHolder1_txtMatKhau").send_keys("abc")
        self.safe_click("ContentPlaceHolder1_txtHoTen").send_keys("Trần Văn Hà")
        self.safe_click("ContentPlaceHolder1_txtNamSinh").send_keys("2012-12-14")
        self.safe_click("ContentPlaceHolder1_txtEmail").send_keys("hauipro123@gmail.com")
        self.safe_click("ContentPlaceHolder1_txtDiaChi").send_keys("DHCN Hà Nội")
        self.safe_click("ContentPlaceHolder1_btDangky")
        WebDriverWait(self.driver, 10).until(
            EC.text_to_be_present_in_element((By.ID, "ContentPlaceHolder1_lblThongBao"), "Nhập số điện thoại"))
        assert "Nhập số điện thoại" in self.driver.find_element(By.ID, "ContentPlaceHolder1_lblThongBao").text

    def test_tC008(self):
        self.driver.get("http://hauiproj.somee.com/Default.aspx")
        self.clean_ads()
        self.safe_click("LinkDK")
        self.safe_click("ContentPlaceHolder1_txtTaiKhoan").send_keys("abc")
        self.safe_click("ContentPlaceHolder1_txtMatKhau").send_keys("abc")
        self.safe_click("ContentPlaceHolder1_txtHoTen").send_keys("Trần Văn Đa")
        self.safe_click("ContentPlaceHolder1_txtNamSinh").send_keys("2008-12-02")
        self.safe_click("ContentPlaceHolder1_txtEmail").send_keys("hauipro123@gmail.com")
        self.safe_click("ContentPlaceHolder1_txtSdt").send_keys("0125478958")
        self.safe_click("ContentPlaceHolder1_btDangky")
        WebDriverWait(self.driver, 10).until(
            EC.text_to_be_present_in_element((By.ID, "ContentPlaceHolder1_lblThongBao"), "Nhập địa chỉ"))
        assert "Nhập địa chỉ" in self.driver.find_element(By.ID, "ContentPlaceHolder1_lblThongBao").text

    def test_tC009(self):
        self.driver.get("http://hauiproj.somee.com/Default.aspx")
        self.clean_ads()
        self.safe_click("LinkDK")
        self.safe_click("ContentPlaceHolder1_txtTaiKhoan").send_keys("abc")
        self.safe_click("ContentPlaceHolder1_txtMatKhau").send_keys("abc")
        self.safe_click("ContentPlaceHolder1_txtHoTen").send_keys("Trần Văn Đa")
        self.safe_click("ContentPlaceHolder1_txtNamSinh").send_keys("2001-12-12")
        self.safe_click("ContentPlaceHolder1_txtEmail").send_keys("hauipro123@gmail.com")
        self.safe_click("ContentPlaceHolder1_txtSdt").send_keys("0125478951")
        self.safe_click("ContentPlaceHolder1_txtDiaChi").send_keys("DHCN Hà Nội")
        self.safe_click("ContentPlaceHolder1_btDangky")
        WebDriverWait(self.driver, 10).until(
            EC.text_to_be_present_in_element((By.ID, "ContentPlaceHolder1_lblThongBao"),
                                             "Tài khoản đã có người sử dụng"))
        assert "Tài khoản đã có người sử dụng" in self.driver.find_element(By.ID,
                                                                           "ContentPlaceHolder1_lblThongBao").text

    def test_tC010(self):
        self.driver.get("http://hauiproj.somee.com/Default.aspx")
        self.clean_ads()
        self.safe_click("LinkDK")
        self.safe_click("ContentPlaceHolder1_txtTaiKhoan").send_keys("vuahaui")
        self.safe_click("ContentPlaceHolder1_txtMatKhau").send_keys("12345")
        self.safe_click("ContentPlaceHolder1_txtHoTen").send_keys("Trần Thị Lan")
        self.safe_click("ContentPlaceHolder1_txtNamSinh").send_keys("1999-10-04")
        # Chọn giới tính
        dropdown = self.driver.find_element(By.ID, "ContentPlaceHolder1_dllGioiTinh")
        dropdown.find_element(By.XPATH, "//option[. = 'Nữ']").click()
        self.safe_click("ContentPlaceHolder1_txtEmail").send_keys("hauipro1234@gmail.com")
        self.safe_click("ContentPlaceHolder1_txtSdt").send_keys("0789451239")
        self.safe_click("ContentPlaceHolder1_txtDiaChi").send_keys("DHCN Hà Nội")
        self.safe_click("ContentPlaceHolder1_btDangky")


# Kích hoạt chạy toàn bộ Class
if __name__ == "__main__":
    pytest.main(["-v", "-s", __file__])