# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBaoTriDanhMuc():
  @classmethod
  def setup_class(cls):
    cls.driver = webdriver.Firefox()
    cls.vars = {}

  @classmethod
  def teardown_class(cls):
    cls.driver.quit()

  def setup_method(self, method):
    pass

  def teardown_method(self, method):
    pass
  
  def test_tC044(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1482, 800)
    self.driver.find_element(By.ID, "LinkDN").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("admin")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("1234")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
  
  def test_tC045(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1482, 754)
    self.driver.find_element(By.ID, "LinkQT").click()
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink5 > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtID").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtID").send_keys("10")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTenDM").send_keys("Kính Cận")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_LinkButton1").click()
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink1 > li").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(6) > li").click()
  
  def test_tC046(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1482, 754)
    self.driver.find_element(By.ID, "LinkQT").click()
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink5 > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtID").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtID").send_keys("1")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTenDM").send_keys("Đồ Điện Tử")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_LinkButton1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".auto-style1 tr:nth-child(3) > td:nth-child(2)").click()
  
  def test_tC047(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1482, 754)
    self.driver.find_element(By.ID, "LinkQT").click()
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink5 > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTenDM").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTenDM").send_keys("Kính Viễn ")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_LinkButton1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".auto-style1 tr:nth-child(3) > td:nth-child(2)").click()
  
  def test_tC048(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1482, 754)
    self.driver.find_element(By.ID, "LinkQT").click()
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink5 > li").click()
    self.driver.find_element(By.CSS_SELECTOR, ".item-data:nth-child(7) .bt-style-chucnang:nth-child(1)").click()
    self.driver.find_element(By.NAME, "ctl00$ContentPlaceHolder1$GridView1$ctl07$ctl01").click()
    self.driver.find_element(By.NAME, "ctl00$ContentPlaceHolder1$GridView1$ctl07$ctl01").send_keys("Đồ Điện Tử Cập Nhật")
    self.driver.find_element(By.NAME, "ctl00$ContentPlaceHolder1$GridView1$ctl07$ctl02").click()
  
  def test_tC049(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1482, 754)
    self.driver.find_element(By.ID, "LinkQT").click()
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink5 > li").click()
    self.driver.find_element(By.CSS_SELECTOR, ".item-data:nth-child(7) .bt-style-chucnang:nth-child(1)").click()
    self.driver.find_element(By.NAME, "ctl00$ContentPlaceHolder1$GridView1$ctl07$ctl01").click()
    self.driver.find_element(By.CSS_SELECTOR, ".item-data:nth-child(7) .bt-style-chucnang:nth-child(2)").click()
  
  def test_tC050(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1482, 754)
    self.driver.find_element(By.ID, "LinkQT").click()
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink5 > li").click()
    self.driver.find_element(By.CSS_SELECTOR, ".item-data:nth-child(7) .bt-style-chucnang:nth-child(2)").click()
  
  def test_tC051(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1482, 754)
    self.driver.find_element(By.ID, "LinkQT").click()
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink5 > li").click()
    self.driver.find_element(By.CSS_SELECTOR, ".item-data:nth-child(2) > td:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".item-data:nth-child(2) .bt-style-chucnang:nth-child(2)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".khung-admin > .khung-phai2-admin")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".khung-admin > .khung-phai2-admin")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".khung-admin > .khung-phai2-admin")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".khung-admin > .khung-phai2-admin").click()
    self.driver.find_element(By.CSS_SELECTOR, ".khung-admin > .khung-phai2-admin").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtID").click()
  
  def test_tC052(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1482, 780)
    self.driver.find_element(By.ID, "LinkQT").click()
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink5 > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtID").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtID").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtID").send_keys("34")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_LinkButton1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".auto-style1 tr:nth-child(3) > td:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".auto-style1 tr:nth-child(3) > td:nth-child(2)").click()
  
  def test_tC053(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1482, 761)
    self.driver.find_element(By.ID, "LinkQT").click()
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink5 > li").click()
    self.driver.find_element(By.ID, "LinkDX").click()
    self.driver.find_element(By.ID, "LinkDN").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("abc")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("abc")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
    self.driver.find_element(By.CSS_SELECTOR, ".menu-ngang").click()
    self.driver.close()
