# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDangNhapDangXuat():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC011(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1516, 816)
    self.driver.find_element(By.ID, "LinkDN").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("haui")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".khung-phai2").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
  
  def test_tC012(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1516, 816)
    self.driver.find_element(By.ID, "LinkDN").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("1234ngaynghiveEM")
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > td:nth-child(2)").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("1234")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
  
  def test_tC013(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1516, 816)
    self.driver.find_element(By.ID, "LinkDN").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("haui")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("1234560")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
  
  def test_tC014(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1516, 816)
    self.driver.find_element(By.ID, "LinkDN").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("1234")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
  
  def test_tC015(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1516, 816)
    self.driver.find_element(By.ID, "LinkDN").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("haui")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
  
  def test_tC016(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1516, 816)
    self.driver.find_element(By.ID, "LinkDN").click()
    self.driver.find_element(By.LINK_TEXT, "Quay lại").click()
  
  def test_tC017(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1516, 816)
    self.driver.find_element(By.ID, "LinkDN").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("haui")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("1234")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
    self.driver.find_element(By.ID, "LinkDX").click()
  
  def test_tC018(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1516, 816)
    self.driver.find_element(By.ID, "LinkDN").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("llallallallalla")
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > td:nth-child(1)").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("oduiago")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
  
  def test_tC019(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1516, 816)
    self.driver.find_element(By.ID, "LinkDN").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
  
  def test_tC020(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1516, 816)
    self.driver.find_element(By.ID, "LinkDN").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("haui")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("1234@@**")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
  
  def test_tC021(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1516, 816)
    self.driver.find_element(By.ID, "LinkDN").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtTaikhoan").send_keys("haui@@**")
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > td:nth-child(2)").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_txtMatkhau").send_keys("1234")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btDangnhap").click()
  
if __name__ == "__main__":
    pytest.main(["-v", "test_dangNhapDangXuat.py"])