# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestQuanLyDatHang():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC022(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(784, 912)
    self.driver.find_element(By.CSS_SELECTOR, ".menu-trai a:nth-child(2) > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btnThanhToan").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtTen_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtTen_0").send_keys("Nguyễn Ngọc Sơn ")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtDienThoai_0").send_keys("0377665655")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtEmail_0").send_keys("nguyenngocson1682k5@gmail.com")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtDiaChi_0").send_keys("nhổn")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_ddlPhuongThuc_0").click()
    dropdown = self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_ddlPhuongThuc_0")
    dropdown.find_element(By.XPATH, "//option[. = 'Chuyển khoản']").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0").send_keys("đóng gói cẩn thận")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_btnThanhToan_0").click()
  
  def test_tC023(self):
    self.driver.get("http://hauiproj.somee.com/Dathang.aspx")
    self.driver.set_window_size(784, 913)
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink1 > li").click()
    self.driver.find_element(By.CSS_SELECTOR, ".menu-trai a:nth-child(4) > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btnThanhToan").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtTen_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtTen_0").send_keys("Nguyễn Ngọc Sơn")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtDienThoai_0").send_keys("0377665655")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtEmail_0").send_keys("nguyenngocson1682k5@gmail.com")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtDiaChi_0").send_keys("nhổn")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_ddlPhuongThuc_0").click()
    dropdown = self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_ddlPhuongThuc_0")
    dropdown.find_element(By.XPATH, "//option[. = 'Chuyển khoản']").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_btnThanhToan_0").click()
    self.driver.close()
  
  def test_tC024(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(784, 912)
    self.driver.find_element(By.CSS_SELECTOR, ".menu-trai a:nth-child(4) > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btnThanhToan").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0").send_keys("đóng gói cẩn thận")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_btnThanhToan_0").click()
  
  def test_tC025(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(784, 913)
    self.driver.find_element(By.CSS_SELECTOR, ".menu-trai a:nth-child(3) > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_2").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_txtSoLuong_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_txtSoLuong_0").send_keys("12")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btnThanhToan").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5)").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_ddlPhuongThuc_0").click()
    dropdown = self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_ddlPhuongThuc_0")
    dropdown.find_element(By.XPATH, "//option[. = 'Chuyển khoản']").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtDiaChi_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtDiaChi_0").send_keys("Nam từ liêm")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0").send_keys("đóng gói cẩn thận")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_btnThanhToan_0").click()
  
  def test_tC026(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(784, 912)
    self.driver.find_element(By.CSS_SELECTOR, ".menu-trai a:nth-child(2) > li").click()
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink4 > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btnThanhToan").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btnTiepTucMuaHang").click()
  
  def test_tC027(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(784, 912)
    self.driver.find_element(By.CSS_SELECTOR, ".menu-trai a:nth-child(3) > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_2").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_txtSoLuong_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_txtSoLuong_0").send_keys("9")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btnThanhToan").click()
    self.driver.find_element(By.CSS_SELECTOR, ".auto-style1 tr:nth-child(2)").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtTen_0").send_keys("Nguyễn Ngọc Sơn ")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtDienThoai_0").send_keys("0377665655")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0").send_keys("đóng gói cân than")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_btnThanhToan_0").click()
  
  def test_tC028(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(784, 912)
    self.driver.find_element(By.CSS_SELECTOR, ".menu-trai a:nth-child(3) > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink4 > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btnThanhToan").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0").send_keys("đóng gói cẩn thận")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_btnThanhToan_0").click()
    self.driver.close()
  
  def test_tC029(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(784, 913)
    self.driver.find_element(By.CSS_SELECTOR, ".menu-trai a:nth-child(2) > li").click()
    self.driver.find_element(By.CSS_SELECTOR, "#ContentPlaceHolder1_DataList1_HyperLink1_0 > .khung-sp > div").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btnTiepTucMuaHang").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_2").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btnThanhToan").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0").send_keys("dsondg gói cânt than")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_btnThanhToan_0").click()
  
  def test_tC030(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(784, 912)
    self.driver.find_element(By.CSS_SELECTOR, ".menu-trai a:nth-child(3) > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_5").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btnThanhToan").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtTen_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtTen_0").send_keys("Nguyễn Ngọc Sơn")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtDienThoai_0").send_keys("0377665655")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtDiaChi_0").send_keys("Nhổn")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_ddlPhuongThuc_0").click()
    dropdown = self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_ddlPhuongThuc_0")
    dropdown.find_element(By.XPATH, "//option[. = 'Chuyển khoản']").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0").send_keys("đóng gói cẩn thận giúp em ")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_btnThanhToan_0").click()
    self.driver.close()
  
  def test_tC031(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(784, 912)
    self.driver.find_element(By.CSS_SELECTOR, ".menu-trai a:nth-child(2) > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_2").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btnTiepTucMuaHang").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_1").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_txtSoLuong_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_txtSoLuong_0").send_keys("13")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btnThanhToan").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_txtGhiChu_0").send_keys("đóng gói cẩn thận cho em nhé")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_dtlThongTinUser_btnThanhToan_0").click()
    self.driver.close()
  
  def test_tC033(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1552, 928)
    self.driver.find_element(By.CSS_SELECTOR, ".menu-trai a:nth-child(2) > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_4").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_txtSoLuong_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_txtSoLuong_0").send_keys("12")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_txtSoLuong_0").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btnThanhToan").click()
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink1 > li").click()
    self.driver.close()
  
