# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestQuanlibanhang():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC01(self):
    self.driver.get("http://hauiproj.somee.com/Giohang.aspx")
    self.driver.set_window_size(1265, 908)
    self.driver.find_element(By.CSS_SELECTOR, ".khung").click()
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink4 > li").click()
  
  def test_tC02(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1265, 908)
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink2 > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Label1_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_txtSoLuong_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_txtSoLuong_0").send_keys("2")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    self.driver.close()
  
  def test_tC03(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1266, 912)
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink2 > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_2").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(8) > .bt-style-chucnang").click()
  
  def test_tC04(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1266, 912)
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink2 > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_gvGioHang_txtSoLuong_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_gvGioHang_txtSoLuong_0").send_keys("0")
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(8) > .bt-style-chucnang").click()
  
  def test_tC05(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1266, 912)
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink2 > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_2").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(9) > .bt-style-chucnang").click()
  
  def test_tC06(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1265, 908)
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink4 > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btnXoaGioHang").click()
  
  def test_tC07(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1265, 908)
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink4 > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_btnThanhToan").click()
  
  def test_tC08(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1265, 908)
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink2 > li").click()
    self.driver.find_element(By.CSS_SELECTOR, "#ContentPlaceHolder1_DataList1_HyperLink1_0 > .khung-sp > div").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_txtSoLuong_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_txtSoLuong_0").send_keys("-1")
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
  
  def test_tC09(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1265, 908)
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink2 > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
  
  def test_tC010(self):
    self.driver.get("http://hauiproj.somee.com/Default.aspx")
    self.driver.set_window_size(1265, 908)
    self.driver.find_element(By.CSS_SELECTOR, "#HyperLink2 > li").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_DataList1_Image1_2").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_Datalist1_btnThemVaoGio_0").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_gvGioHang_txtSoLuong_1").click()
    self.driver.find_element(By.ID, "ContentPlaceHolder1_gvGioHang_txtSoLuong_1").send_keys("5")
    self.driver.find_element(By.CSS_SELECTOR, ".item-data:nth-child(3) > td:nth-child(8) > .bt-style-chucnang").click()
  
